// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACoTCabD3_8kYYAY3mjowrGDGbPbpvduY',
    appId: '1:637889612938:web:533ab1f1100e466c5fb173',
    messagingSenderId: '637889612938',
    projectId: 'nativestay-77105',
    authDomain: 'nativestay-77105.firebaseapp.com',
    storageBucket: 'nativestay-77105.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfiZbeFD-ZJfRRJYDbxJ7DhsuL7w8Dny4',
    appId: '1:637889612938:android:a85ac3878f7f50ce5fb173',
    messagingSenderId: '637889612938',
    projectId: 'nativestay-77105',
    storageBucket: 'nativestay-77105.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA63Hrw1vC1JBHz7vr2SJLz008K-DfggpA',
    appId: '1:637889612938:ios:192e15673442b0335fb173',
    messagingSenderId: '637889612938',
    projectId: 'nativestay-77105',
    storageBucket: 'nativestay-77105.firebasestorage.app',
    iosClientId: '637889612938-djk4ja0lmm4g4fn63qb6q8liot8jkkmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA63Hrw1vC1JBHz7vr2SJLz008K-DfggpA',
    appId: '1:637889612938:ios:192e15673442b0335fb173',
    messagingSenderId: '637889612938',
    projectId: 'nativestay-77105',
    storageBucket: 'nativestay-77105.firebasestorage.app',
    iosClientId: '637889612938-djk4ja0lmm4g4fn63qb6q8liot8jkkmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACoTCabD3_8kYYAY3mjowrGDGbPbpvduY',
    appId: '1:637889612938:web:19a3c4f2528cea5b5fb173',
    messagingSenderId: '637889612938',
    projectId: 'nativestay-77105',
    authDomain: 'nativestay-77105.firebaseapp.com',
    storageBucket: 'nativestay-77105.firebasestorage.app',
  );
}
